// <auto-generated />
namespace Vidly.com.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class genretypes : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(genretypes));
        
        string IMigrationMetadata.Id
        {
            get { return "202101311527177_genretypes"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
